[versions]
kotlin = "1.6.10"
compose-jb = "1.0.1"
buildconfig = "3.0.2"
mirai = "2.9.2"
yamlkt = "0.10.2"
json = "1.3.2"
junit = "4.13"

[libraries]
plugin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
plugin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-composejb = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-jb" }
plugin-buildconfig = { group = "com.github.gmazzo", name = "gradle-buildconfig-plugin", version.ref = "buildconfig" }

mirai-core = { group = "net.mamoe", name = "mirai-core", version.ref = "mirai" }
mirai-console = { group = "net.mamoe", name = "mirai-console", version.ref = "mirai" }
serialization-yaml = { group = "net.mamoe.yamlkt", name = "yamlkt", version.ref = "yamlkt" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "json" }
junit4 = { group = "junit", name = "junit", version.ref = "junit" }

kotlin-coroutinues-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.5.0" }